export const GET_USERS="GET_USERS";
export const ADD_USER="ADD_USER";
export const DELETE_USER="DELETE_USER"
export const CHANGE_PERM="CHANGE_PERM"

export const LOGIN="LOGIN"
export const LOGOUT="LOGOUT"

export const GET_CONTACTS="GET_CONTACTS"
export const ADD_CONTACT="ADD_CONTACT"
export const EDIT_CONTACTF="EDIT_CONTACTF"
export const DELETE_CONTACT="DELETE_CONTACT"
export const FILTER_CONTACTS="FILTER_CONTACTS"
export const CLEAR_FILTER_CONTACTS="CLEAR_FILTER_CONTACTS"
export const NEXT_FIFTYC="NEXT_FIFTYC"
export const NEXT_FIFTYF="NEXT_FIFTYF"
export const PREVIOUS_FIFTY="PREVIOUS_FIFTY"
export const RESET_NEXT="RESET_NEXT"

export const GET_EMPLOYEES="GET_EMPLOYEES"
export const ADD_EMPLOYEE="ADD_EMPLOYEE"
export const EDIT_EMPLOYEEF="EDIT_EMPLOYEEF"
export const DELETE_EMPLOYEE="DELETE_EMPLOYEE"
export const FILTER_EMPLOYEES="FILTER_EMPLOYEES"
export const CLEAR_FILTER_EMPLOYEES="CLEAR_FILTER_EMPLOYEES"
export const NEXT_FIFTYE="NEXT_FIFTYE"
export const NEXT_FIFTYFE="NEXT_FIFTYFE"
export const PREVIOUS_FIFTYE="PREVIOUS_FIFTYE"
export const RESET_NEXTE="RESET_NEXTE"

export const CLEAR_ERROR="CLEAR_ERROR"